# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-05 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PotentialPhotographers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=128, unique=True)),
                ('lastname', models.CharField(max_length=100)),
            ],
        ),
    ]
